export const baseAction = {
    SET_USERS: 'SET_USERS',
    SET_POSTS: 'SET_POSTS',
    SET_COMMENTS: 'SET_COMMENTS',
    SET_USER_TRIGGER: 'SET_USER_TRIGGER',
    SET_POST_TRIGGER: 'SET_POST_TRIGGER',
    SET_COMMENT_TRIGGER: 'SET_COMMENT_TRIGGER',
    SET_USER_INFO: 'SET_USER_INFO'
};




